apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1poc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-1poc@sha256:cacbe22e6a1e74ea2bd9ad9988d614f13023fc0cff1f97c153078a0d5a14d504
        name: my-nodejs
        resources: {}
status: {}
